version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 719872330848.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=719872330848.dkr.ecr.ap-south-1.amazonaws.com/uttara-registry
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-${COMMIT_HASH:=latest}

  build:
    commands:
      - echo build stated on 'date'
      - echo building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build completed on 'date'
      - echo pushing the docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"aws-code-pipeline-docker-ecr","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json
    artifacts:
      files:
        - imageDetail.json
        - target/aws-code-pipeline-docker-ecr.jar

